site-name = "YASSG Documentation"
trailing-slashes = true
footer-notice = "Copyright &copy; 2017 Niklas Rosenstein"
google-analytics = "UA-102556838-1"
github-repository = "NiklasRosenstein/yassg"
content-directory = "../docs"
static-directory = false
